import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import AudioControls from '@/features/audio-recorder'
import type { ReactElement } from 'react'
import SideNavBar from '@/features/navigation'
import { Heading } from '@chakra-ui/react'
import PermissionsProvider from '@/features/permissions'
import { useRouter } from 'next/router'
import Widget from '@/features/widget'

export default function Index(): ReactElement {
  return (
    <>
      <Head>
        <title>Vietnamese Language Tools</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SideNavBar>HOME</SideNavBar>
    </>
  )
}
