import Head from 'next/head'
import type { ReactElement } from 'react'
import SideNavBar from '@/features/navigation'
import { Text } from '@chakra-ui/react'

export default function Index(): ReactElement {
  return (
    <>
      <Head>
        <title>Vietnamese Language Tools</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SideNavBar>
        <Text>Home</Text>
      </SideNavBar>
    </>
  )
}
