import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { useDisclosure } from "@mantine/hooks"
import { AppShell } from "@mantine/core"
import AppConfig from "../config"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const [mobileOpened, { toggle: toggleMobile }] = useDisclosure()
	const [desktopOpened, { toggle: toggleDesktop }] = useDisclosure(true)

	const [isOpen, { toggle }] = useDisclosure()

	return (
		<html lang="en">
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link
					href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Calistoga&family=Cormorant+Upright:wght@300;400;500;600;700&family=Spectral+SC:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Yeseva+One&family=Yrsa:ital,wght@0,300..700;1,300..700&display=swap"
					rel="stylesheet"
				/>
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<title>VLT</title>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
