import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { useDisclosure } from "@mantine/hooks"
import { AppShell } from "@mantine/core"
import AppConfig from "../config"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const [mobileOpened, { toggle: toggleMobile }] = useDisclosure()
	const [desktopOpened, { toggle: toggleDesktop }] = useDisclosure(true)

	const [isOpen, { toggle }] = useDisclosure()

	return (
		<html lang="en">
			<head>
				<meta charSet="UTF-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<title>VLT</title>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
