/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"

// Create Virtual Routes

const ReaderLazyImport = createFileRoute("/reader")()
const DicionaryLazyImport = createFileRoute("/dicionary")()

// Create/Update Routes

const ReaderLazyRoute = ReaderLazyImport.update({
	id: "/reader",
	path: "/reader",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/reader.lazy").then((d) => d.Route))

const DicionaryLazyRoute = DicionaryLazyImport.update({
	id: "/dicionary",
	path: "/dicionary",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/dicionary.lazy").then((d) => d.Route))

const IndexRoute = IndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/"
			path: "/"
			fullPath: "/"
			preLoaderRoute: typeof IndexImport
			parentRoute: typeof rootRoute
		}
		"/dicionary": {
			id: "/dicionary"
			path: "/dicionary"
			fullPath: "/dicionary"
			preLoaderRoute: typeof DicionaryLazyImport
			parentRoute: typeof rootRoute
		}
		"/reader": {
			id: "/reader"
			path: "/reader"
			fullPath: "/reader"
			preLoaderRoute: typeof ReaderLazyImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute
	"/dicionary": typeof DicionaryLazyRoute
	"/reader": typeof ReaderLazyRoute
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute
	"/dicionary": typeof DicionaryLazyRoute
	"/reader": typeof ReaderLazyRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	"/": typeof IndexRoute
	"/dicionary": typeof DicionaryLazyRoute
	"/reader": typeof ReaderLazyRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: "/" | "/dicionary" | "/reader"
	fileRoutesByTo: FileRoutesByTo
	to: "/" | "/dicionary" | "/reader"
	id: "__root__" | "/" | "/dicionary" | "/reader"
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute
	DicionaryLazyRoute: typeof DicionaryLazyRoute
	ReaderLazyRoute: typeof ReaderLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	DicionaryLazyRoute: DicionaryLazyRoute,
	ReaderLazyRoute: ReaderLazyRoute,
}

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/dicionary",
        "/reader"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/dicionary": {
      "filePath": "dicionary.lazy.tsx"
    },
    "/reader": {
      "filePath": "reader.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
