/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ReaderLazyImport = createFileRoute('/reader')()
const HomeLazyImport = createFileRoute('/home')()
const DicionaryLazyImport = createFileRoute('/dicionary')()

// Create/Update Routes

const ReaderLazyRoute = ReaderLazyImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/reader.lazy').then((d) => d.Route))

const HomeLazyRoute = HomeLazyImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))

const DicionaryLazyRoute = DicionaryLazyImport.update({
  id: '/dicionary',
  path: '/dicionary',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dicionary.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dicionary': {
      id: '/dicionary'
      path: '/dicionary'
      fullPath: '/dicionary'
      preLoaderRoute: typeof DicionaryLazyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dicionary': typeof DicionaryLazyRoute
  '/home': typeof HomeLazyRoute
  '/reader': typeof ReaderLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dicionary': typeof DicionaryLazyRoute
  '/home': typeof HomeLazyRoute
  '/reader': typeof ReaderLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dicionary': typeof DicionaryLazyRoute
  '/home': typeof HomeLazyRoute
  '/reader': typeof ReaderLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dicionary' | '/home' | '/reader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dicionary' | '/home' | '/reader'
  id: '__root__' | '/' | '/dicionary' | '/home' | '/reader'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DicionaryLazyRoute: typeof DicionaryLazyRoute
  HomeLazyRoute: typeof HomeLazyRoute
  ReaderLazyRoute: typeof ReaderLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DicionaryLazyRoute: DicionaryLazyRoute,
  HomeLazyRoute: HomeLazyRoute,
  ReaderLazyRoute: ReaderLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/dicionary",
        "/home",
        "/reader"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/dicionary": {
      "filePath": "dicionary.lazy.tsx"
    },
    "/home": {
      "filePath": "home.lazy.tsx"
    },
    "/reader": {
      "filePath": "reader.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
