/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const SavedLazyRouteImport = createFileRoute('/saved')()
const ReaderLazyRouteImport = createFileRoute('/reader')()
const HomeLazyRouteImport = createFileRoute('/home')()
const DictionaryLazyRouteImport = createFileRoute('/dictionary')()
const ChatLazyRouteImport = createFileRoute('/chat')()

const SavedLazyRoute = SavedLazyRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/saved.lazy').then((d) => d.Route))
const ReaderLazyRoute = ReaderLazyRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reader.lazy').then((d) => d.Route))
const HomeLazyRoute = HomeLazyRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))
const DictionaryLazyRoute = DictionaryLazyRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dictionary.lazy').then((d) => d.Route))
const ChatLazyRoute = ChatLazyRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatLazyRoute
  '/dictionary': typeof DictionaryLazyRoute
  '/home': typeof HomeLazyRoute
  '/reader': typeof ReaderLazyRoute
  '/saved': typeof SavedLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatLazyRoute
  '/dictionary': typeof DictionaryLazyRoute
  '/home': typeof HomeLazyRoute
  '/reader': typeof ReaderLazyRoute
  '/saved': typeof SavedLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatLazyRoute
  '/dictionary': typeof DictionaryLazyRoute
  '/home': typeof HomeLazyRoute
  '/reader': typeof ReaderLazyRoute
  '/saved': typeof SavedLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/dictionary' | '/home' | '/reader' | '/saved'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/dictionary' | '/home' | '/reader' | '/saved'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dictionary'
    | '/home'
    | '/reader'
    | '/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatLazyRoute: typeof ChatLazyRoute
  DictionaryLazyRoute: typeof DictionaryLazyRoute
  HomeLazyRoute: typeof HomeLazyRoute
  ReaderLazyRoute: typeof ReaderLazyRoute
  SavedLazyRoute: typeof SavedLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatLazyRoute: ChatLazyRoute,
  DictionaryLazyRoute: DictionaryLazyRoute,
  HomeLazyRoute: HomeLazyRoute,
  ReaderLazyRoute: ReaderLazyRoute,
  SavedLazyRoute: SavedLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
