import Head from 'next/head'
import type { ReactElement } from 'react'
import SideNavBar from '@/features/navigation'
import PermissionsProvider from '@/features/permissions'
import Widget from '@/features/widget'
import { TRANSCRIPTION } from '@/features/widget/index'

export default function Index(): ReactElement {
  return (
    <>
      <Head>
        <title>Vietnamese Language Tools</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Raleway:wght@100;300&display=swap'
          rel='stylesheet'
        />
      </Head>
      <SideNavBar>
        <PermissionsProvider>
          <Widget type={TRANSCRIPTION} left />
        </PermissionsProvider>
      </SideNavBar>
    </>
  )
}
