import Head from 'next/head'
import { useCallback, type ReactElement } from 'react'
import PermissionsProvider from '@/features/permissions'
import WaveSection from '@/features/common/components/WaveSection'
import AuroraSection from '@/features/common/components/AuroraSection'
import Widget from '@/features/widget'
import { TRANSCRIPTION } from '@/features/widget/index'
import { Flex, Text, Box, Center } from '@chakra-ui/react'
import * as styles from './bars.module.css'

type DescriptiveTextBlocksProps = {
  title: string | null
  description: string | null
  content: ReactElement
}
const DescriptiveTextBlocks = ({
  title,
  description,
  content,
}: DescriptiveTextBlocksProps): ReactElement => {
  return (
    <Center margin={'1em'} padding={'1em'} flexDirection={'column'} w={'45vw'} bg={'white'}>
      <Text
        fontFamily={'Alexandria'}
        padding={'0.2em'}
        color={'black'}
        fontWeight={800}
        fontSize={'4xl'}
      >
        {title ?? title}
      </Text>
      {description && (
        <Text
          fontFamily={'Didact Gothic'}
          textAlign={'center'}
          padding={'0.5em'}
          minH={'25vh'}
          color={'black'}
          fontWeight={400}
          fontSize={'1.2em'}
        >
          {description}
        </Text>
      )}
      {!!content && content}
    </Center>
  )
}

export default function Index(): ReactElement {
  const handleRevealWidget = useCallback((event) => {
    console.log(event)
  }, [])

  const descriptionSections = []

  return (
    <>
      <Head>
        <title>Vietnamese Language Tools</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        {/* <script
          src='https://cdn.jsdelivr.net/npm/vara@1.4.0/lib/vara.min.js'
          type='text/javascript'
        ></script>
        <script src='https://cdn.jsdelivr.net/gh/foobar404/wave.js/dist/bundle.js'></script> */}
      </Head>
      <PermissionsProvider>
        <Box gap={'10vh'}>
          <WaveSection />
          <AuroraSection />
          <Center padding={'3em'}>
            <DescriptiveTextBlocks
              title={'Speak. Listen. Write.'}
              description={
                'Experience the ease of converting spoken words into text, simplifying language capture for a variety of applications.'
              }
            />
          </Center>

          <Center id={'transcribe-detail'} as={'section'} marginTop={'15em'} h={'60vh'} w={'100%'}>
            <DescriptiveTextBlocks
              title={'Bạn nói câu này có đúng không?'}
              description={'Repeat the sentence below'}
              content={
                <Center w={'80vw'} onMouseDown={handleRevealWidget}>
                  <Text fontSize={'4em'} fontWeight={700} fontFamily={'Fragen'}>
                    Mặt trời lặn và biển lặng
                  </Text>
                </Center>
              }
            />
          </Center>
          <Center id={'transcribe-detail'} as={'section'} marginTop={'15em'} h={'60vh'} w={'100%'}>
            <DescriptiveTextBlocks
              title={'Try me out now!'}
              description={null}
              content={
                <Center maxH={'30vh'}>
                  <Widget type={TRANSCRIPTION} left />
                </Center>
              }
            />
          </Center>
        </Box>
      </PermissionsProvider>
    </>
  )
}
